// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc1
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceGetter_GetPrice_FullMethodName = "/PriceGetter/GetPrice"
)

// PriceGetterClient is the client API for PriceGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceGetterClient interface {
	GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
}

type priceGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceGetterClient(cc grpc.ClientConnInterface) PriceGetterClient {
	return &priceGetterClient{cc}
}

func (c *priceGetterClient) GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, PriceGetter_GetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceGetterServer is the server API for PriceGetter service.
// All implementations must embed UnimplementedPriceGetterServer
// for forward compatibility.
type PriceGetterServer interface {
	GetPrice(context.Context, *PriceRequest) (*PriceResponse, error)
	mustEmbedUnimplementedPriceGetterServer()
}

// UnimplementedPriceGetterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceGetterServer struct{}

func (UnimplementedPriceGetterServer) GetPrice(context.Context, *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedPriceGetterServer) mustEmbedUnimplementedPriceGetterServer() {}
func (UnimplementedPriceGetterServer) testEmbeddedByValue()                     {}

// UnsafePriceGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceGetterServer will
// result in compilation errors.
type UnsafePriceGetterServer interface {
	mustEmbedUnimplementedPriceGetterServer()
}

func RegisterPriceGetterServer(s grpc.ServiceRegistrar, srv PriceGetterServer) {
	// If the following call pancis, it indicates UnimplementedPriceGetterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceGetter_ServiceDesc, srv)
}

func _PriceGetter_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceGetterServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceGetter_GetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceGetterServer).GetPrice(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceGetter_ServiceDesc is the grpc.ServiceDesc for PriceGetter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceGetter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PriceGetter",
	HandlerType: (*PriceGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _PriceGetter_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
